### ISSUE TITLE
Add BabyDeerAGI

### ISSUE THREAD

**Issue by miurla** [miurla/babyagi-ui#101]
## Reference
- Twitter: https://twitter.com/yoheinakajima/status/1666313838868992001
- GitHub: https://github.com/yoheinakajima/babyagi/blob/main/classic/BabyDeerAGI.py

## TODO
- [x] Putting together a flow
- [x] Add Executer
- [x] Add a menu
- [x] Implement Execution
- [x] Tools
    - [x] Update web-search
    - [x] Addition of user-input
- [x] Parallel execution support
