### ISSUE TITLE
Improve mobile layout

### ISSUE THREAD

**Issue by miurla** [miurla/babyagi-ui#54]
## TODO

- [x] Overlapping select content
- [x] Adjusting overall margins
- [x] Menu open by default
- [x] Adjust project title layout
